---
# Location where configuration files will be stored.
config_dir: "~/containers"

# Feature flags
blocky_enable: true
adguard_enable: false
open_speed_test_enable: false
watchtower_enable: true

# AdGuard configuration
# https://github.com/AdguardTeam/Adguardhome/wiki/Configuration#configuration-file
adguard_user: "victor"
adguard_password: "PASSWORD_HASH_PLACEHOLDER" # https://github.com/AdguardTeam/Adguardhome/wiki/Configuration#password-reset
adguard_upstream_dns:
  - "h3://dns.google/dns-query"
adguard_bootstrap_dns:
  - "192.168.100.1"
adguard_fallback_dns:
  - "https://cloudflare-dns.com/dns-query"
  - "https://anycast.dns.nextdns.io"
  - "https://dns10.quad9.net/dns-query"

# Network configuration
# https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html
network_conn_name: "eth0"
network_interface: "eth0"
network_dns4:
  - "8.8.8.8"
  - "8.8.4.4"
network_dns6:
  - "2001:4860:4860::8888"
  - "2001:4860:4860::8844"

# Unattended-upgrades configuration
# https://github.com/hifis-net/ansible-collection-toolkit/tree/main/roles/unattended_upgrades
unattended_systemd_timer_override: true
# apt-daily-upgrade timer
unattended_apt_daily_upgrade_oncalendar: "*-*-* 03:30"
unattended_apt_daily_upgrade_randomizeddelaysec: "0"
unattended_origins_patterns:
  - "origin=Debian,codename=${distro_codename},label=Debian-Security"
  - "origin=Raspberry Pi Foundation,codename=${distro_codename},label=Raspberry Pi Foundation"
  - "origin=Docker"
unattended_automatic_reboot: true
