---
- name: Check if Docker is already present.
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_command_result

- name: Download Docker install convenience script.
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: "0775"
  when: docker_command_result.rc == 1

- name: Configure Docker's package repositories.
  ansible.builtin.command: /tmp/get-docker.sh --setup-repo
  environment:
    CHANNEL: stable
  when: docker_command_result.rc == 1
  changed_when: docker_command_result.rc == 1

- name: Ensure Docker is installed (Debian).
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Ensure Docker is started.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: "Ensure user is added to the docker group: {{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

# reset_connection doesn't support conditionals.
- name: Reset connection so docker group is picked up.
  ansible.builtin.meta: reset_connection
